const BaseCommand = require('../../utils/structures/BaseCommand');
const Discord = require("discord.js");
const talkedRecently = new Set();

module.exports = class SteamCommand extends BaseCommand {
  constructor() {
    super('hulu', 'movies', []);
  }

  async run(client, message, args) {

    const wrong = new Discord.MessageEmbed()
      .setTitle("Success!")
      .setDescription(`**Hey** ${message.author.username}, I Sent You The Account Check Your Dm!`)
      .setFooter("Onyx gen")
      .setColor("GREEN")


    const timer = new Discord.MessageEmbed()
      .setTitle("COOLDOWN IS ON PROGRESS!")
      .setDescription(`**Hey** ${message.author.username}, Please wait __**15**__ minutes before trying Again.`)
      .setFooter("Buy Premium For 5 Minutes Cooldown")
      .setColor("RED")


     


    if (talkedRecently.has(message.author.id)) {
      message.channel.send(timer);
    } else {



      // the user can type the command ... your command code goes here :)


      
      //steam
     

      const choices = [
        
        "dmajewski21@gmail.com:tippmann | Name = Dan | Gender = male | Subscription = 1076888552",
        "tinamillerlloyd@gmail.com:soulmate1 | Name = Tina | Gender = female | Subscription = 1110442984",
        "teddyr94@yahoo.com:Beauty@94 | Name = ashley chevere | Gender = female | Subscription = Hulu  ",
        "wc6878@gmail.com:7896wh | Name = Chris | Gender = male | Subscription = Hulu  ",
        "almcclellan2@aol.com:bailey1221 | Name = Almcclellan | Gender = female | Subscription = Hulu  ",
        "Steve_turner51@yahoo.com:Gh0stR0b0 | Name = Stephen | Gender = male | Subscription = Disney bundle with Hulu (No Ads)  ",
        "kfoley87@aol.com:kf181709 | Name = Kevin | Gender = male | Subscription = Hulu  ",
        "minijenni97@yahoo.com:Princess26 | Name = ? | Gender = ? | Subscription = Hulu  ",
        "falonhendrick@gmail.com:Penelope38 | Name = falon | Gender = female | Subscription = Hulu with Ads  ",
        "sclynch71@gmail.com:hunter98 | Name = Stacey Lynch | Gender = female | Subscription = Hulu  ",
        "lauren_massing@yahoo.com:coco1234 | Name = ? | Gender = ? | Subscription = Hulu  ",
        "taliatru5@gmail.com:talia tru | Name = Talia | Gender = female | Subscription = Hulu, STARZ®  ",
        "trisharichard10@gmail.com:abikaty04 | Name = Trisha | Gender = female | Subscription = Hulu with Ads  ",
        "baakins@ptd.net:cara1975 | Name = ᴘʟᴀsᴍᴀ | Gender = male | Subscription = Hulu, Disney+, and ESPN+  ",
        "gomezroselia92@gmail.com:Javierm1102 | Name = ROSY | Gender = female | Subscription = Hulu + Live TV, SHOWTIME®, CINEMAX®, ST",
        "lunaderr@gmail.com:Raiders1 | Name = Richard | Gender = male | Subscription = 1053671",
        "slb2jd@virginia.edu:ashley00 | Name = stephanie | Gender = female | Subscription = Hulu  ",
        "raquelbarnes22@yahoo.com:jennifer1 | Name = Raquel | Gender = female | Subscription = 70733",
        "chroniccomics@gmail.com:timdrake1 | Name = ? | Gender = ? | Subscription = Hulu  ",
        "ohheyitzlilyx3@gmail.com:jonasbabe66 | Name = ? | Gender = ? | Subscription = Hulu  ",
        "mms3742@yahoo.com:master0422 | Name = Megan | Gender = female | Subscription = Hulu  ",
        "evan.oster@gmail.com:5.9L345t | Name = Evan | Gender = male | Subscription = Hulu (No Ads)  ",
        "hollowayfab42@gmail.com:Chickie10 | Name = Riley | Gender = male | Subscription = Hulu  ",
        "differentladyj23@yahoo.com:Kamarion04 | Name = Mignon | Gender = female | Subscription = 1383072744",
        "kraftab@sou.edu:Oliver525 | Name = Abby kraft | Gender = female | Subscription = Hulu, Disney+, and ESPN+  ",
        "hansen_chelsey21@yahoo.com:fordie97 | Name = chelsey hansen | Gender = female | Subscription = Hulu (No Ads)  ",
        "magdalena.acevedo@yahoo.com:Ktowie1! | Name = Sparky | Gender = male | Subscription = 1053671",
        "fredapplegate2@gmail.com:redsoxs15467 | Name = ? | Gender = ? | Subscription = Hulu  ",
        "freedyjr3225@gmail.com:coryisawesome3225 | Name = Cory | Gender = male | Subscription = Hulu (No Ads), HBO®  ",
        "aj.adamjennings@gmail.com:Donandajluv8387 | Name = ? | Gender = ? | Subscription = Hulu  ",
        "bstokes51@gmail.com:bp2718108 | Name = Bill | Gender = male | Subscription = Hulu with Ads  ",
        "mironconstruction@yahoo.com:Alex2007 | Name = David | Gender = male | Subscription = Hulu, Disney+, and ESPN+  ",
        "afou200@hotmail.com:salama25 | Name = Afou | Gender =  | Subscription = 1053671",
        "moralesluz70@yahoo.com:ashjos07 | Name = Luz | Gender = female | Subscription = Hulu  ",
        "speedyjack10@gmail.com:thor2007 | Name = jack | Gender = male | Subscription = Hulu with Ads  ",
        "krishawnaking@comcast.net:Keyahsmom#1 | Name = Krishawna | Gender = female | Subscription = Disney bundle with Hulu (No Ads) ", 
        "dwndel@aol.com:lindseyleigh | Name = lindsey | Gender = female | Subscription = Hulu (No Ads)  ",
        "taylorcosner123@gmail.com:imovie123 | Name = Taylor | Gender = female | Subscription = Hulu with Ads  ",
        "benfucht@gmail.com:pbg357 | Name = ? | Gender = ? | Subscription = Hulu  ",
        "cottomiguel12@gmail.com:junjocotto3 | Name = ? | Gender = ? | Subscription = Hulu  ",
        "guoingonline@yahoo.com:angelajg | Name = Jason | Gender = male | Subscription = Hulu  ",
        "jadekealohi@yahoo.com:1biohazard | Name = ronson | Gender = male | Subscription = Disney bundle with Hulu (No Ads)  ",
        "jrzy101@comcast.net:Jonjon001 | Name = ? | Gender = ? | Subscription = Hulu  ",
        "alanrossjr89@gmail.com:Alan1357 | Name = Alan | Gender = male | Subscription = Hulu  ",
        "madison.wilcox22@yahoo.com:maddie9220 | Name = Madison | Gender = female | Subscription = Hulu  ",
        "Blacksheep1026@gmail.com:102610Sh | Name = shaun | Gender = male | Subscription = Hulu  ",
        "elizabethn2003@outlook.com:alaska2003 | Name = Elizabeth | Gender = female | Subscription = Hulu  ",
        "zwsmith1999@aol.com:Zsmith75451 | Name = Zach Smith | Gender = male | Subscription = Hulu with Ads  ",
        "gizellecarlota@aol.com:love7song | Name = gizelle | Gender = female | Subscription = Hulu, Disney+, and ESPN+  ",
        "tyler.m.barbosa@gmail.com:tigersareawesome | Name = tyler | Gender = male | Subscription = Hulu  ",
        "hrabusak@gmail.com:KHrabusa1999 | Name = khrabusa | Gender = male | Subscription = Hulu  ",
        "alexisgclark@gmail.com:Clarks12 | Name = ? | Gender = ? | Subscription = Hulu  ",
        "mallaryb2609@yahoo.com:Baylor42 | Name = mal bloodworth | Gender = female | Subscription = Hulu, Live TV, HBO®  ",
        "marcela424cope@gmail.com:sauce424 | Name = Marcela Morelos | Gender = female | Subscription = Hulu  ",
        "chercasky_romina@hotmail.com:luna1551 | Name = Ky Thomas | Gender = male | Subscription = Hulu  ",
        "kelsco24@hotmail.com:macaroni24 | Name = Kelsie | Gender = female | Subscription = Hulu, Disney+, and ESPN+  ",
        "sanja.amiric@gmail.com:Stefan22 | Name = Sanja | Gender = female | Subscription = Hulu  ",
        "fcabaseball10@gmail.com:sports | Name = Jack | Gender = male | Subscription = Hulu  ",
        "chrisgonz987@yahoo.com:Sonic987 | Name = Christopher Gonzalez | Gender = male | Subscription = Hulu (No Ads)  ",
        "peterbiltcowboy@yahoo.com:2807rexp | Name = Rex Packard | Gender = male | Subscription = 1053671",
        "sniper113078@aol.com:dolce1978 | Name = ? | Gender = ? | Subscription = Hulu  ",
        "madeleinehaines1999@gmail.com:mrose0406 | Name = Madeleine | Gender = female | Subscription = Hulu  ",
        "trakroxmysox333@aol.com:Cupcakes3 | Name = Sophia | Gender = female | Subscription = Hulu (No Ads), HBO®  ",
        "megan@lookatme-films.com:Miles1118 | Name = Megan | Gender = female | Subscription = Hulu with Ads  ",
        "benavidez19@hotmail.com:firebird | Name = ? | Gender = ? | Subscription = Hulu  ",
        "natalietsai@live.com:Cookie123! | Name = ? | Gender = ? | Subscription = Hulu  ",
        "flipnick2@gmail.com:flipperlove2 | Name = Nicky | Gender = female | Subscription = Hulu, Live TV, STARZ®  ",
        "tigger7928@yahoo.com:alexie01 | Name = ? | Gender = ? | Subscription = Hulu  ",
        "lisasanto1072@verizon.net:Kayla2008 | Name = Lisa | Gender = female | Subscription = Hulu with Ads  ",
        "boomersooner813@yahoo.com:kaiden1029 | Name = Dylan Young | Gender = male | Subscription = Hulu  ",
        "dv_smith1210@yahoo.com:smitty12 | Name = Scott smith | Gender = male | Subscription = Hulu, Disney+, and ESPN+  ",
        "dczimmerman@ec.rr.com:duckie2870 | Name = Donnie | Gender =  | Subscription = Hulu with Ads  ",
        "btrfly1004@aol.com:Llkl0828 | Name = Lori | Gender = female | Subscription = Hulu with Ads  ",
        "cindybrewer161@gmail.com:@3ogPink | Name = Cindy | Gender = female | Subscription = Hulu (No Ads)  ",
        "twolter@cox.net:Turbo3jts | Name = Tony | Gender = male | Subscription = Hulu  ",
        "hollowayfab42@gmail.com:Chickie10 | Name = Riley | Gender = male | Subscription = Hulu  ",
        "kristenh624@gmail.com:Mshill123 | Name = Kristen | Gender = female | Subscription = Hulu, Live TV  ",
        "hiland234@hotmail.com:Hiland234 | Name = Devin | Gender = male | Subscription = Hulu with Ads  ",
        "taylorghemme@comcast.net:midji218 | Name = taylorhemme | Gender = female | Subscription = Hulu  ",
        "joslynroddy@gmail.com:Babygirl01 | Name = Joslyn | Gender = female | Subscription = Hulu (No Ads), SHOWTIME®  ",
        "nick.citrano@me.com:Ncitrano1 | Name = Nick | Gender = male | Subscription = Hulu  ",
        "tristanshaw7@gmail.com:Tshaw1996 | Name = Tristan | Gender = male | Subscription = Hulu (No Ads)  ",
        "lunaderr@gmail.com:Raiders1 | Name = Richard | Gender = male | Subscription = 1053671",
        "xinandra91@yahoo.com:alejan91 | Name = ale | Gender = female | Subscription = Hulu, Disney+, and ESPN+  ",
        "gypsybreeze100@yahoo.com:bep8cen1 | Name = ? | Gender = ? | Subscription = Hulu  ",
        "blaine.loyola94@yahoo.com:kyzer1994 | Name = Blaine | Gender =  | Subscription = Hulu (No Ads)  ",
        "shelleyrobbins69@yahoo.com:mr7350 | Name = Shelley | Gender = female | Subscription = Hulu (No Ads), HBO®, STARZ®  ",
        "jgross005@hotmail.com:taxboss | Name = Jorge | Gender = male | Subscription = Hulu with Ads  ",
        "madynelson123@gmail.com:madysen2001 | Name = MADY | Gender = female | Subscription = Hulu with Ads  ",
        "jwelzel@seidata.com:919191ky | Name = jwelzel-us | Gender = female | Subscription = Hulu, Disney+, and ESPN+  ",
        "upandragon47@yahoo.com:powerlite | Name = Ed | Gender = male | Subscription = Hulu with Ads  ",
        "carsensmith1@gmail.com:Lvac5822! | Name = Carsen | Gender = male | Subscription = Disney bundle with Hulu (No Ads)  ",
        "lovecharne22@gmail.com:poohbear22 | Name = Nekeshia | Gender = female | Subscription = Hulu, STARZ®  ",
        "tianator22@gmail.com:tmmblue00 | Name = Empire is coming | Gender = female | Subscription = Hulu  ",
        "gatortoby@comcast.net:ellie23 | Name = Momma | Gender = female | Subscription = Hulu with Ads  ",
        "mspiebaker@yahoo.com:Rantrant24 | Name = DONNA | Gender = female | Subscription = Hulu with Ads  ",
        "sherrie.d.young@gmail.com:firebrand | Name = Mom_Dad | Gender =  | Subscription = 1110442984",
        "asr1213@gmail.com:ballet97 | Name = Ariadne Suzanne Roberts | Gender = female | Subscription = Hulu (No Ads)  ",
        "highmoonwinterhearth@hotmail.com:allforme | Name = main | Gender = male | Subscription = Hulu, Disney+, and ESPN+  ",
        "niicole.guerrero@gmail.com:nena1994 | Name = Nicole | Gender = female | Subscription = Hulu (No Ads)  ",
        "s_nieto93722@yahoo.com:Shutson3910 | Name = Stacy | Gender = female | Subscription = 70528",
        "cuddles2234@aol.com:snowball101 | Name = Abigail | Gender = female | Subscription = Hulu  ",
        "kellyrhaley@gmail.com:Cooper26. | Name = Kelly | Gender = female | Subscription = Hulu (No Ads), HBO®  ",
        "hannahbanana032003@yahoo.com:Banana21 | Name = Hannah | Gender = female | Subscription = 70723",
        "lgatlin28@gmail.com:Gatlin28 | Name = Laron | Gender = male | Subscription = Hulu, Disney+, and ESPN+  ",
        "mjm8700@yahoo.com:bball87 | Name = ? | Gender = ? | Subscription = Hulu  ",
        "christella0587@yahoo.ca:rouge123 | Name = ? | Gender = ? | Subscription = Hulu  ",
        "mjpettis13@gmail.com:vq23rar5 | Name = Jesse | Gender = male | Subscription = Hulu with Ads  ",
        "showgurl101@yahoo.com:551241m | Name = ? | Gender = ? | Subscription = Hulu  ",
        "kkbuehrer79@hotmail.com:!QAZ2wsx | Name = ? | Gender = ? | Subscription = Hulu  ",
        "c-ba@live.com:trustinno1 | Name = ? | Gender = ? | Subscription = Hulu  ",
        "c.isabel.martinelli@gmail.com:carolina89 | Name = carolina | Gender = female | Subscription = Hulu (No Ads)  ",
        "neil_reid@dsl.pipex.com:ootaking | Name = ? | Gender = ? | Subscription = Hulu  ",
        "jaegosney@gmail.com:June1991 | Name = Jae | Gender = female | Subscription = Hulu, Disney+, and ESPN+  ",
        "kfontenot14@yahoo.com:k07160716 | Name = Kristi Williams Fontenot | Gender = female | Subscription = Hulu + Live TV, HBO®, CI",
        "vanessatorrez@msn.com:poetic10 | Name = Vanessa | Gender =  | Subscription = Hulu (No Ads)  ",
        "briar.cochran@gmail.com:briar001 | Name = Briar Cochran | Gender = male | Subscription = Hulu  ",
        "hdevoine@yahoo.com:hidorian4 | Name = Hilda | Gender = female | Subscription = Hulu, Disney+, and ESPN+  ",
        "triumphbonnie71@yahoo.com:87vanagon | Name = Anthony | Gender = male | Subscription = Hulu, Live TV  ",
        "b.bgurl@yahoo.com:danielle94 | Name = Jessica | Gender = female | Subscription = Hulu with Ads  ",
        "kmallen081100@gmail.com:ka081100 | Name = Keara | Gender = female | Subscription = Hulu, STARZ®  ",
        "mdstall118@gmail.com:sta11ings | Name = Marilyn | Gender =  | Subscription = Hulu with Ads  ",
        "cottomiguel12@gmail.com:junjocotto3 | Name = ? | Gender = ? | Subscription = Hulu  ",
        "stef2kids@gmail.com:my2kids | Name = stefanie | Gender = female | Subscription = Hulu, Disney+, and ESPN+  ",
        "kalexanderb96@hotmail.com:dipperdopper32 | Name = Karina | Gender = female | Subscription = Hulu with Ads  ",
        "daltondurbin7@gmail.com:football90 | Name = ? | Gender = ? | Subscription = Hulu  ",
        "natrob1030@gmail.com:Wing6700! | Name = Natalie | Gender = female | Subscription = Hulu, Disney+, and ESPN+  ",
        "emma.a.blackson@gmail.com:HungerGames1 | Name = Emma | Gender = female | Subscription = Hulu (No Ads)  ",
        "liliannebailey@gmail.com:hicool7 | Name = lbailey | Gender = female | Subscription = Hulu, Live TV, HBO®  ",
        "llawtum@gmail.com:Munchkin1 | Name = Loey | Gender = female | Subscription = Hulu (No Ads), HBO®  ",
        "mcenteec2@gmail.com:pippen33 | Name = Colleen McEntee | Gender = female | Subscription = Hulu  ",
        "rzepinski14@gmail.com:Ryan0414 | Name = Ryan | Gender = male | Subscription = Hulu with Ads  ",
        "lori.grace@att.net:0099lori | Name = Lori | Gender = female | Subscription = Hulu, Live TV  ",
        "emma.a.blackson@gmail.com:HungerGames1 | Name = Emma | Gender = female | Subscription = Hulu (No Ads)  ",
        "jzw1800@yahoo.com:Baseball7 | Name = Justin | Gender = male | Subscription = Hulu, Disney+, and ESPN+  ",
        "scoyaw@yahoo.com:Mathew23 | Name = Stephanie Salazar | Gender = male | Subscription = Hulu, Disney+, and ESPN+  ",
        "sjj25@yahoo.com:t2ww1a25 | Name = Steven | Gender = male | Subscription = Hulu (No Ads)  ",
        "Mzsmith1973@aol.com:Ania0801 | Name = Mecki Smith | Gender = female | Subscription = Hulu, Disney+, and ESPN+  ",
        "masonross1998@hotmail.com:Mamabear1 | Name = Mason | Gender =  | Subscription = Hulu (No Ads)  ",
        "ballher71@gmail.com:felicia21 | Name = Felicia | Gender = female | Subscription = 68732",
        "matthewhkim123@gmail.com:Pinewood1 | Name = matthewhkim123 | Gender = male | Subscription = Hulu  ",
        "reslowik@me.com:Dance123456 | Name = Reece | Gender = female | Subscription = Hulu with Ads  ",
        "acbell66@gmail.com:Southlake15 | Name = ? | Gender = ? | Subscription = Hulu  ",
        "airineek@aol.com:eis4erin | Name = ? | Gender = ? | Subscription = Hulu  ",
        "julienneyabut@yahoo.com:Yabsterzs26! | Name = Juliane | Gender = female | Subscription = Hulu with Ads  ",
        "mari_sela100@yahoo.com:yazdely1004 | Name = Marisela | Gender = female | Subscription = 305136616",
        "chareasejackson@gmail.com:Shylas#1 | Name = Charease Williams | Gender = female | Subscription = Hulu with Ads  ",
        "nick.citrano@me.com:Ncitrano1 | Name = Nick | Gender = male | Subscription = Hulu  ",
        "emily.moon42@gmail.com:jesse1234 | Name = Emily Skrede | Gender = female | Subscription = Disney bundle with Hulu (No Ads)  ",
        "dakjak27@yahoo.com:Chaice27 | Name = James | Gender = male | Subscription = Disney bundle with Hulu (No Ads)  ",
        "chelebellie215@gmail.com:coors1 | Name = Michele | Gender = female | Subscription = Disney bundle with Hulu (No Ads)  ",
        "jmalicea99@gmail.com:Catnero1 | Name = jmalicea99 | Gender = male | Subscription = Hulu  ",
        "abigailtrautt@yahoo.com:hrrjac21 | Name = Abigail | Gender = female | Subscription = Hulu  ",
        "kenttt1998@gmail.com:Nippon1998 | Name = Kent Tarver | Gender = male | Subscription = Hulu (No Ads)  ",
        "moneymike1958@gmail.com:taylor47 | Name = Michael | Gender = male | Subscription = 70733",
        "brandyr703@yahoo.com:pooty620 | Name = Brandy | Gender = female | Subscription = Hulu  ",
        "latanya_anthony@hotmail.com:morgan6474 | Name = ? | Gender = ? | Subscription = Hulu  ",
        "noah.starwars7@gmail.com:1327Ea776$ | Name = Noah | Gender = male | Subscription = Hulu  ",
        "james-lawrence998@hotmail.com:Rooster321$ | Name = James | Gender = male | Subscription = Hulu  ",
        "anedwards1989@gmail.com:Eagleband7 | Name = amanda | Gender = female | Subscription = Hulu (No Ads)  ",
        "laurendaccnt@gmail.com:Chichi1! | Name = Lauren | Gender = female | Subscription = 70504",
        "rgleaf51@yahoo.com:Rsgleaf51 | Name = Randy | Gender = male | Subscription = Disney bundle with Hulu (No Ads)  ",
        "lmahmoodi@ucdavis.edu:leila95m | Name = Leila | Gender = female | Subscription = Hulu + Live TV, SHOWTIME®, CINEMAX®, STARZ®,", 
        "daniellesatler@yahoo.com:Ugagymnast77! | Name = Danielle | Gender = female | Subscription = Hulu  ",
        "relmofzen@gmail.com:Perfect1 | Name = ? | Gender = ? | Subscription = Hulu  ",
        "joemuschaweck@yahoo.com:Fenway1022! | Name = Joseph | Gender = male | Subscription = 1076888552",
        "lori.grace@att.net:0099lori | Name = Lori | Gender = female | Subscription = Hulu, Live TV  ",
        "snowjohnson5@hotmail.com:saigecooper5 | Name = Michael | Gender = male | Subscription = Hulu, Disney+, and ESPN+  ",
        "skloya97@yahoo.com:9515loya | Name = Perla | Gender = female | Subscription = Hulu, Live TV  ",
        "rslohg6@gmail.com:webgem11 | Name = Sarah | Gender = female | Subscription = Hulu with Ads  ",
        "tresslynmills@gmail.com:870194 | Name = tresslyn | Gender = female | Subscription = 70733",
        "tweety_lu@yahoo.com:leelee10 | Name = Maria | Gender = female | Subscription = Hulu with Ads  ",
        "akuklar@gmail.com:Confused4 | Name = william | Gender = male | Subscription = Hulu, Live TV  ",
        "bdemao@gmail.com:Buddy911 | Name = Bernadette | Gender = female | Subscription = Hulu (No Ads), HBO®  ",
        "schump2154@gmail.com:glam2154 | Name = Schump | Gender = female | Subscription = Hulu  ",
        "paige.sumida@gmail.com:elle4l0ve | Name = ? | Gender = ? | Subscription = Hulu  ",
        "cgrlovestaz@yahoo.com:Jordyn52 | Name = Love | Gender =  | Subscription = Hulu, Disney+, and ESPN+  ",
        "sbhutchison@bellsouth.net:Gracie@#1 | Name = Sara | Gender = female | Subscription = Hulu (No Ads)  ",
        "jdl_1977@yahoo.com:intrepid1 | Name = Jen | Gender =  | Subscription = 70528",
        "pointerj13@yahoo.com:mano0126 | Name = Jonathan | Gender = male | Subscription = Hulu with Ads  ",
        "mer820@gmail.com:QWqwqw12 | Name = Michael Rohr | Gender = male | Subscription = Hulu  ",
        "ivanjcarrion@yahoo.com:jayden24 | Name = ivan | Gender = male | Subscription = Hulu  ",
        "blastrax@gmail.com:0115d8cf | Name = ? | Gender = ? | Subscription = Hulu  ",
        "nrun13@hotmail.com:Lululove1 | Name = Nicole | Gender =  | Subscription = Hulu (No Ads)  ",
        "angie_polanco@yahoo.com:Jackueline123 | Name = Angie | Gender = female | Subscription = Hulu (No Ads)  ",
        "brandyr703@yahoo.com:pooty620 | Name = Brandy | Gender = female | Subscription = Hulu  ",
        "aleblanc1988@gmail.com:timothy2007 | Name = ? | Gender = ? | Subscription = Hulu  ",
        "stranskyj@msn.com:Joseph01 | Name = ? | Gender = ? | Subscription = Hulu  ",
        "vekv@earthlink.net:jonathan1 | Name = Robert | Gender = male | Subscription = Hulu  ",
        "yarymariew@gmail.com:8649angel | Name = Yarymarie | Gender = female | Subscription = Hulu with Ads  ",
        "drphil97@aol.com:aaron422 | Name = philip | Gender = male | Subscription = Hulu with Ads  ",
        "maryarmbruster@msn.com:Tessbear1$ | Name = Mary | Gender = female | Subscription = Hulu with Ads  ",
        "kellyrhaley@gmail.com:Cooper26. | Name = Kelly | Gender = female | Subscription = Hulu (No Ads), HBO®  ",
        "lauren.lewis122@gmail.com:lauren12296 | Name = laurenrlewiss | Gender = female | Subscription = Hulu  ",
        "lagarydomingo@gmail.com:Corvette2 | Name = LD | Gender = male | Subscription = Hulu, Disney+, and ESPN+  ",
        "gadams77@hotmail.com:florida1 | Name = ? | Gender = ? | Subscription = Hulu  ",
        "micaylamichaels@gmail.com:Maddie0506 | Name = Micayla | Gender = female | Subscription = Hulu, Disney+, and ESPN+  ",
        "ansleycam@gmail.com:bray3333 | Name = Lori | Gender = female | Subscription = Hulu  ",
        "Hannahcarney00@gmail.com:Hanpat11 | Name = Hannah Alexis | Gender = female | Subscription = Hulu, Disney+, and ESPN+  ",
        "madynelson123@gmail.com:madysen2001 | Name = MADY | Gender = female | Subscription = Hulu with Ads  ",
        "shortteemarketing@yahoo.com:Platos80328 | Name = Shorty | Gender = male | Subscription = Disney bundle with Hulu (No Ads)  ",
        "nick.citrano@me.com:Ncitrano1 | Name = Nick | Gender = male | Subscription = Hulu  ",
        "daltondurbin7@gmail.com:football90 | Name = ? | Gender = ? | Subscription = Hulu  ",
        "alleghenyaquaticalliance@hotmail.com:flaming420 | Name = Mike | Gender = male | Subscription = Hulu  ",
        "suzetteroldan16@gmail.com:Wemadeit1. | Name = Suzette | Gender = female | Subscription = Hulu  ",
        "Jefffernandez808@yahoo.com:kalima55 | Name = Jeff | Gender = male | Subscription = Hulu (No Ads)  ",
        "sofia.allarakhia@gmail.com:longbeach06 | Name = Banana | Gender = female | Subscription = Hulu (No Ads)  ",
        "coltonrandolph98@gmail.com:Alexander0806! | Name = Colton Randolph | Gender = male | Subscription = Hulu, Disney+, and ESPN+ ", 
        "scottlynfuller@icloud.com:103571Sf | Name = Fam | Gender = female | Subscription = Hulu (No Ads)  ",
        "taj48@bellsouth.net:Kelvinjr16 | Name = Teresa | Gender = female | Subscription = Hulu, Disney+, and ESPN+  ",
        "kalaskani@gmail.com:salinson | Name = ? | Gender = ? | Subscription = Hulu  ",
        "jlperry0312@yahoo.com:stinky1 | Name = Jamie | Gender = female | Subscription = Hulu (No Ads)  ",
        "ajandresen@yahoo.com:SkouSen2 | Name = ? | Gender = ? | Subscription = Hulu  ",
        "crysmllr@yahoo.com:hershie1 | Name = ? | Gender = ? | Subscription = Hulu  ",
        "sarasp25@aol.com:smpsoccer25 | Name = Sarasp25 | Gender = female | Subscription = Hulu  ",
        "chapjunk522@att.net:madison522 | Name = Susan | Gender = female | Subscription = Hulu (No Ads), HBO®  ",
        "1970portlandtrailblazers@gmail.com:ashmic8890 | Name = Tammy | Gender = female | Subscription = Hulu (No Ads)  ",
        "kayjhurst@yahoo.com:Hottie09! | Name = Kaylee | Gender = female | Subscription = Hulu, Disney+, and ESPN+  ",
        "ihlij@icloud.com:victoria1 | Name = Julie | Gender = female | Subscription = Hulu with Ads  ",
        "floresandrew102@gmail.com:boba1226 | Name = Andrew | Gender = male | Subscription = Disney bundle with Hulu (No Ads)  ",
        "whitneybbarth@yahoo.com:easton420 | Name = Whitney | Gender = female | Subscription = Hulu, Disney+, and ESPN+  ",
        "akametalbeast@yahoo.com:12101822 | Name = Mike | Gender = male | Subscription = Hulu, Disney+, and ESPN+  ",
        "Judith.duran22@yahoo.com:July221996 | Name = Judith | Gender = female | Subscription = 70723",
        "aschinlever@yahoo.com:76calif | Name = Austin | Gender = male | Subscription = Hulu  ",
        "atruluck89@yahoo.com:Chris12107 | Name = Amber | Gender = female | Subscription = Hulu, Disney+, and ESPN+  ",
        "mozic3@gmail.com:Gtr#54321 | Name = ? | Gender = ? | Subscription = Hulu  ",
        "jesfrog91401@yahoo.com:bilfrog91401 | Name = Jessica Graves | Gender = female | Subscription = Hulu with Ads  ",
        "pattifinegan@bex.net:michael1 | Name = Patti finegan | Gender =  | Subscription = Hulu, Disney+, and ESPN+  ",
        "tylerwadelamb@hotmail.com:210506wa | Name = ? | Gender = ? | Subscription = Hulu  ",
        "brandonshelton.me@gmail.com:thomas78 | Name = Brandon | Gender = male | Subscription = 1378878440",
        "tanie0915@gmail.com:panama01 | Name = Tanisha Lewis | Gender = female | Subscription = 7341032",
        "drphil97@aol.com:aaron422 | Name = philip | Gender = male | Subscription = Hulu with Ads  ",
        "marianne.roe@gmail.com:9485Walw! | Name = Marianne Roe | Gender = female | Subscription = Hulu, Disney+, and ESPN+  ",
        "maymay@gvtc.com:hellokitty | Name = meagannnlewis | Gender = female | Subscription = Hulu  ",
        "chunsteeve@yahoo.com:Risefrom4311 | Name = Steve | Gender = male | Subscription = Hulu (No Ads), HBO®  ",
        "javier.pagan@live.com:Javiman93 | Name = Javier Pagan | Gender = male | Subscription = Hulu (No Ads)  ",
        "grsavans@hotmail.com:Frost000 | Name = zerkseez | Gender = male | Subscription = Hulu  ",
        "flipnick2@gmail.com:flipperlove2 | Name = Nicky | Gender = female | Subscription = Hulu, Live TV, STARZ®  ",
        "opivyjohnperry1@yahoo.com:Joestrummer1 | Name = John | Gender = male | Subscription = 2054161384",
        "mcardona7476@gmail.com:ortiz1992 | Name = mary | Gender = female | Subscription = 70618",
        "jubjubtheiguana7@gmail.com:dulap777 | Name = Amity | Gender = female | Subscription = Hulu, Disney+, and ESPN+  ",
        "ryanferdon17@yahoo.com:Walnut2015 | Name = Ryan | Gender = male | Subscription = Hulu with Ads  ",
        "ahouston984@gmail.com:akcB2639 | Name = Amanda | Gender =  | Subscription = Hulu, Disney+, and ESPN+  ",
        "sarasp25@aol.com:smpsoccer25 | Name = Sarasp25 | Gender = female | Subscription = Hulu  ",
        "elzurdoalezard@hotmail.com:Mear0398 | Name = Manuel | Gender = male | Subscription = Hulu (No Ads)  ",
        "nat.reeder@yahoo.com:ndwr5660 | Name = ? | Gender = ? | Subscription = Hulu  ",
        "jawanmcdougald@yahoo.com:janiya01 | Name = ? | Gender = ? | Subscription = Hulu  ",
        "feli.davis@gmail.com:fefe4040 | Name = Felicia | Gender = female | Subscription = Hulu with Ads  ",
        "isabelw@ntelos.net:091200 | Name = ? | Gender = ? | Subscription = Hulu  ",
        "sqhadden@bellsouth.net:macielyn1 | Name = Stephanie Q Hadden | Gender = male | Subscription = Hulu, Disney+, and ESPN+  ",
        "jasonakillian@gmail.com:lauren88 | Name = Jason | Gender = male | Subscription = Hulu with Ads  ",
        "missalexander99@yahoo.com:LLbball1313 | Name = Nikki | Gender = female | Subscription = Hulu + Live TV, HBO®, CINEMAX®  ",
        "karamfarrell@msn.com:777haley | Name = Kara Farrell | Gender = female | Subscription = 70723",
        "sofia.allarakhia@gmail.com:longbeach06 | Name = Banana | Gender = female | Subscription = Hulu (No Ads)  ",
        "les.vega.sl@gmail.com:rajiv315 | Name = Rog | Gender = male | Subscription = Hulu with Ads  ",
        "kayla.isbel97@gmail.com:999kaykay | Name = Kayla | Gender = female | Subscription = Hulu  ",
        "dannipeel.peel@gmail.com:Peel3221 | Name = ? | Gender = ? | Subscription = Hulu  ",
        "oscar.paramo@me.com:chavodel8 | Name = Oscar | Gender = male | Subscription = Hulu  ",
        "sarah2561@sbcglobal.net:sweet87 | Name = Sarah | Gender = female | Subscription = Hulu  ",
        "rodriguezyasmine12@gmail.com:yasminemarie9600 | Name = Yasmine | Gender = female | Subscription = Hulu (No Ads)  ",
        "brittany.lauren.craig@gmail.com:Neonblue8 | Name = Brittany | Gender = female | Subscription = 1880097768",
        "malcombrito@yahoo.com:sahory1007 | Name = Adriana | Gender = female | Subscription = Hulu  ",
        "cody4u092793@yahoo.com:jghs2012 | Name = ? | Gender = ? | Subscription = Hulu  ",
        "meller@linbeck.com:ellerx5 | Name = Mikki | Gender = female | Subscription = 305136616",
        "kathollomon@hotmail.com:stewil | Name = Kat | Gender = female | Subscription = Hulu with Ads  ",
        "aschoonfield@aol.com:Amanda123 | Name = Amanda Ruth | Gender = female | Subscription = Hulu with Ads  ",
        "kjyue@me.com:Kathleen1 | Name = Kathleen | Gender = female | Subscription = Hulu, STARZ®  ",
        "jderosa95@yahoo.com:maggie123 | Name = ? | Gender = ? | Subscription = Hulu  ",
        "dreamerstill3@gmail.com:japanesemaple11 | Name = Jason | Gender = male | Subscription = Hulu  ",
        "kasbeth07@gmail.com:ksandra1 | Name = kassandra | Gender = female | Subscription = Hulu (No Ads)  ",
        "leeandy2190@yahoo.com:Samlee101 | Name = Andy Lee | Gender = male | Subscription = Hulu  ",
        "christin_r_sherwood@yahoo.com:123molly | Name = Christin Sherwood | Gender = female | Subscription = Hulu, Disney+, and ESPN+",  
        "fireball51198@aol.com:pandabear1998 | Name = Sierra | Gender = female | Subscription = Hulu with Ads  ",
        "qpike536@gmail.com:Greenpig2014 | Name = Quoleman | Gender = male | Subscription = Hulu with Ads  ",
        "jredman98@gmail.com:Jennanate4 | Name = Jenna | Gender = female | Subscription = Hulu (No Ads)  ",
        "chareasejackson@gmail.com:Shylas#1 | Name = Charease Williams | Gender = female | Subscription = Hulu with Ads  ",
        "lyriccat5780@gmail.com:Michelle5780 | Name =  | Gender = female | Subscription = Hulu (No Ads)  ",
        "pruitta@comcast.net:cecilia1 | Name = Anna | Gender = female | Subscription = Hulu with Ads  ",
        "mystanine@gmail.com:201316 | Name = ? | Gender = ? | Subscription = Hulu  ",
        "jlicht7599@aol.com:02tahoe | Name = Amy | Gender = female | Subscription = Hulu with Ads  ",
        "sbellmore@charter.net:mumsie | Name = ? | Gender = ? | Subscription = Hulu  ",
        "joyhill1782@gmail.com:3Oakland | Name = joy | Gender = female | Subscription = Hulu, Disney+, and ESPN+  ",
        "baiteybop@yahoo.com:monkeylover | Name = Bailey | Gender = female | Subscription = Hulu with Ads  ",
        "tonya.acord@gmail.com:Zion0522 | Name = tonya | Gender = female | Subscription = Hulu with Ads  ",
        "typhoonray19@gmail.com:stardust123 | Name = ? | Gender = ? | Subscription = Hulu  ",
        "tuckerfoust@rocketmail.com:Dylan1995 | Name = Tucker Foust | Gender = male | Subscription = Hulu, Disney+, and ESPN+  ",
        "zachvetterkind@outlook.com:November2999 | Name = Zach | Gender = male | Subscription = Hulu (No Ads), HBO®, STARZ®  ",
        "abigailcyndal@yahoo.com:Miami115 | Name = Laura | Gender = female | Subscription = Disney bundle with Hulu (No Ads)  ",
        "michelledmohr@hotmail.com:highgrove | Name = Michelle | Gender = female | Subscription = 70723",
        "oliviajx123@icloud.com:roxiedog | Name = olivia | Gender = female | Subscription = 1076888552",
        "piperkallman@yahoo.com:Nukem1223 | Name = Piper Kallman | Gender = female | Subscription = Hulu  ",
        "makpaulivan@yahoo.com:wxyz0987 | Name = Paul | Gender = male | Subscription = Hulu  ",
        "acbell66@gmail.com:Southlake15 | Name = ? | Gender = ? | Subscription = Hulu  ",
        "aleblanc1988@gmail.com:timothy2007 | Name = ? | Gender = ? | Subscription = Hulu  ",
        "Kimberly.wall@ccboe.net:jeremy546 | Name = ? | Gender = ? | Subscription = Hulu  ",
        "gcharrington1124@gmail.com:emu23spa | Name = Gabby | Gender = female | Subscription = 2121270248",
        "tink23j@gmail.com:Teamwork12 | Name = Stacey | Gender = female | Subscription = Hulu, Disney+, and ESPN+  ",
        "joslynroddy@gmail.com:Babygirl01 | Name = Joslyn | Gender = female | Subscription = Hulu (No Ads), SHOWTIME®  ",
        "christfreak92@hotmail.com:Hotthing92 | Name = Tyler | Gender = male | Subscription = Hulu  ",
        "zman.landau@gmail.com:ilikepie9 | Name = Zachary Landau | Gender = male | Subscription = Hulu  ",
        "normarodriguezz@yahoo.com:mando6210 | Name = Norma | Gender = female | Subscription = Hulu, Disney+, and ESPN+  ",
        "jacob.t1389@gmail.com:maxima1389 | Name = Jacob Tejeda | Gender = male | Subscription = 1315963880",
        "dquanid@gmail.com:isiah123 | Name = Dquan | Gender = male | Subscription = Hulu with Ads  ",
        "dorrian24allen@gmail.com:Lamont1995 | Name = ? | Gender = ? | Subscription = Hulu  ",
        "alexisgclark@gmail.com:Clarks12 | Name = ? | Gender = ? | Subscription = Hulu  ",
        "llcannell@gmail.com:Milkbowl1 | Name = Lindy | Gender = female | Subscription = 1349518312",
        "Alana.singleton1010@gmail.com:Alana1010 | Name = Alana | Gender = female | Subscription = Hulu with Ads  ",
        "jamesrshaffer3@gmail.com:Chloe5dog | Name = James Shaffer | Gender = male | Subscription = Hulu  ",
        "jjmoseman24@gmail.com:Jesuscalvo1 | Name = Jesus | Gender = male | Subscription = Hulu (No Ads)  ",
        "sandrahdz209@gmail.com:joeryan123 | Name = sandra | Gender = female | Subscription = Hulu with Ads  ",
        "alacransote2@aol.com:pitufa2010 | Name = Victor barraza | Gender = male | Subscription = Hulu  ",
        "abdiel.aldana@live.com:3force30123 | Name = Abdiel | Gender = male | Subscription = Hulu  ",
        "nsjaimes@hotmail.com:kamilaj1 | Name = Nidia | Gender = female | Subscription = Hulu  ",
        "kirstylinzee@gmail.com:ROjo121. | Name = K | Gender =  | Subscription = Hulu, Live TV  ",
        "rivas.vivian@yahoo.com:reid777 | Name = Vivian | Gender = female | Subscription = Hulu  ",
        "dzbougere@yahoo.com:Summertime23 | Name = Rondell Smith | Gender = male | Subscription = Hulu with Ads  ",
        "katehermanson33@yahoo.com:Basketball33 | Name = Kate Hermanson | Gender = female | Subscription = Hulu  ",
        "gutierrezkarina1713@yahoo.com:Samuel1713 | Name = Karina | Gender = female | Subscription = Disney bundle with Hulu (No Ads) ", 
        "sminecraft403@gmail.com:hotdog03 | Name = ? | Gender = ? | Subscription = Hulu  ",
        "zachvetterkind@outlook.com:November2999 | Name = Zach | Gender = male | Subscription = Hulu (No Ads), HBO®, STARZ®  ",
        "kasbeth07@gmail.com:ksandra1 | Name = kassandra | Gender = female | Subscription = Hulu (No Ads)  ",
        "juniatacrossings@comcast.net:juniata | Name = Paula | Gender = female | Subscription = Hulu (No Ads)  ",
        "sherileemiller1984@outlook.com:Asshole1 | Name = ? | Gender = ? | Subscription = Hulu  ",
        "sophiaespinoza@gmail.com:Smurf1210 | Name = Casei | Gender = male | Subscription = Hulu + Live TV, SHOWTIME®, CINEMAX®, STARZ",
        "lburgess03@yahoo.com:josiemolly | Name = Lisa | Gender = female | Subscription = Disney bundle with Hulu (No Ads)  ",
        "aplumbr@gmail.com:Poppa1993 | Name = alex | Gender = male | Subscription = Hulu  ",
        "margieu@bellsouth.net:peacock3 | Name = Margie | Gender = female | Subscription = Hulu (No Ads)  ",
        "kjay5181@gmail.com:989123rain | Name = katie johns | Gender = female | Subscription = Hulu with Ads  ",
        "alexandriaalder@yahoo.com:Azlinn12 | Name = Alexandria | Gender = female | Subscription = Hulu  ",

      ];
      const response = choices[Math.floor(Math.random() * choices.length)];

      const non = new Discord.MessageEmbed()
      .setTitle("Something Went Wrong")
      .setDescription("You Can Not Generate, You Have To BE Whitelisted Dm A Admin!")
      .setFooter("Onyx Gen")
      .setColor("RED")
     

      const done = new Discord.MessageEmbed()
      .setTitle("Heres Your Account!")
      .setDescription(response + " You can Regenerate After 15 Minutes!")
      .setFooter("Buy Premium For 5 Minutes Cooldown")
      .setColor("GREEN")


      if (!message.member.roles.cache.find(r => r.name === "Whitelisted")) return message.channel.send(non);
      if (message.member.roles.cache.find(r => r.name === "Whitelisted")) 
      message.author.send(done);
      message.channel.send(wrong);


      // Adds the user to the set so that they can't talk for a minute
      talkedRecently.add(message.author.id);
      setTimeout(() => {
        // Removes the user from the set after a minute
        talkedRecently.delete(message.author.id);
      }, 900000);
    }


  }
}